
#-----------------------------------------------#
#             Bombastic Projectiles
#
#                    Cutzuu
#-----------------------------------------------#

#-----------------------------------------------#
#                 General Options
#-----------------------------------------------#


#ENABLE THIS IF YOU JUST WANT TO BLOW STUFF UP! NO CONFIGS
# - All players / projectiles / mobs can cause explosions.
# - Blocks will break regardless of settings/perms.
# - Block Drops are disabled.
# - Protection Lists are still active.
# - Named Mobs are not safe.
# - Only Global Value is active.
FreeMode: false

#If true, Permissions and Features must be both granted/enabled.
#Permissions do not limit mobs if mob-explode toggles are enabled.
RequirePermission: false

#Explosive Power for every projectile.
#MobImpact and CustomImpact override Global if either are enabled.
GlobalImpact: 5

#If enabled, GlobalImpact will be ignored. Vice Versa.
CustomImpact: false

#These blocks are immune regardless of any perm/toggle.
ProtectedBlocks:
  - NULL
  - CHEST
  - TRAPPED_CHEST
  - BEACON

#BP will not operate in any world of your choice.
ProtectedWorlds:
  - NULL
  - world_peaceful
  - world_plots
  - uhc_oasis

#These entities are immune regardless of any perm/toggle.
ProtectedEntities:
  - NULL
  - PARROT
  - ITEM_FRAME
  - PAINTING


#-----------------------------------------------#
#               Explosion Features
#-----------------------------------------------#

#Similar to Ghast fireball explosions.
Fire: false

#Should destroyed blocks drop into items?
DropItems: false

#NOTE: Players cannot bypass WorldGuard Region but Mobs can,To fix that, set other-explosions to false in your Region Flags.
#/rg info regionName then Flags.
#PlayerBreakBlock Toggle does NOT bypass permissions if permission is are Required.
MobBreakBlocks: true
PlayerBreakBlocks: true

#This ONLY prevents BP Explosive Damage. Any entity can still get hurt by players hitting or any other regular explosions.
HurtMobs: false
HurtPlayer: false
HurtNamedMobs: false


#-----------------------------------------------#
#                   Mob Options
#-----------------------------------------------#

#Mobs can trigger the explosive EFFECT if they hit an entity or block.
#They are still limited by BreakBlocks and hurting other mobs/players.
mobs-Explode-Entities: false
mobs-Explode-Blocks: false

#If false, mobs will use GlobalImpact if CustomImpact is not enabled.
MobImpact: false
#Explosive Power exclusive to Mobs.
MobImpactDamage: 2


#-----------------------------------------------#
#               Projectile Toggles
#-----------------------------------------------#
Egg: false
Arrow: true
Potion: false
Trident: false
Snowball: false
ExpBottle: false
WindCharge: false
Enderpearl: false
FishingBobber: false


#-----------------------------------------------#
#               Projectile Impacts
#
#            MUST ENABLE CustomImpact
#-----------------------------------------------#
Egg-Impact: 2
Arrow-Impact: 5
Potion-Impact: 3
Trident-Impact: 10
Snowball-Impact: 2
ExpBottle-Impact: 3
WindCharge-Impact: 0
Enderpearl-Impact: 0
FishingBobber-Impact: 3


#-----------------------------------------------#
#             Miscellaneous Toggles
#-----------------------------------------------#

#Not recommended for public servers, used for debugging.
verbose: false
